---
#- debug: msg="{{ hostvars[groups['network'][0]] }}"

#- debug: msg="{{ hostvars[groups['network'][1]] }}"

#- debug: msg="{{ hostvars[groups['network'][2]] }}"

#- debug: msg="{{ hostvars[groups['network'][3]] }}"

- name: Install python on all instances 4
  shell: >
    echo {{ hostvars[item].ansible_host }};
    ssh ubuntu@{{ hostvars[item].ansible_host }} -i "{{ lookup('env', 'SSH_KEY') }}" -o StrictHostKeyChecking=no
    'while lsof /var/lib/dpkg/lock-frontend; do sleep 10; done;'
    'sudo apt-get update -y;'
    'while lsof /var/lib/dpkg/lock-frontend; do sleep 10; done;'
    'sudo apt-get install python -y;'
    'while lsof /var/lib/dpkg/lock-frontend; do sleep 10; done;'
    'sudo apt-get install python2-minimal -y;'
    'while lsof /var/lib/dpkg/lock-frontend; do sleep 10; done;'
  with_items: "{{ groups['network'] }}"
  args:
    creates: "{{ lookup('env', 'INVENTORY_DIR_PATH') }}/install_python.ignore"

- name: Mark python installed
  file:
      path: "{{ lookup('env', 'INVENTORY_DIR_PATH') }}/install_python.ignore"
      state: touch
      mode: 664
