---

- name: Run script to start storage
  shell: |
    go env -w GO111MODULE=auto
    nohup ./run_storage.sh &>/dev/null & sleep 1
  args:
    chdir: "{{ scripts_path }}"
    executable: /bin/bash

#- name: Run script to start orderer
#  shell: |
#    go env -w GO111MODULE=auto
#    ./run_storage.sh
#  args:
#    chdir: "{{ scripts_path }}"
#  async: 200
#  poll: 20