---

- name: Check if Endorser is running
  stat: 
    path: "{{ root_path }}/running.ignore"
  register: running

- include_tasks: tasks/start_endorser.yaml
  when: running.stat.exists == False

- name: Mark Endorser as running
  file:
      path: "{{ root_path }}/running.ignore"
      state: touch
      mode: 664
