---

- name: check if artifacts already exist
  stat: 
    path: "{{ inventory_path }}/artifacts.ignore"
  register: artifacts

- include_tasks: tasks/create_artifacts.yaml
  when: artifacts.stat.exists == False

- include_tasks: tasks/update_network.yaml

  
- name: Mark artifacts created
  file:
      path: "{{ inventory_path }}/artifacts.ignore"
      state: touch
      mode: 664
